// <auto-generated />
using System;
using ConnorBourbon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConnorBourbon.Migrations
{
    [DbContext(typeof(BourbonContext))]
    [Migration("20230319171805_NullableTagId")]
    partial class NullableTagId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ConnorBourbon.Models.Bourbon", b =>
                {
                    b.Property<int>("BourbonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("BourbonId");

                    b.HasIndex("BrandId");

                    b.ToTable("Bourbons");
                });

            modelBuilder.Entity("ConnorBourbon.Models.BourbonTag", b =>
                {
                    b.Property<int>("BourbonTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("BourbonId")
                        .HasColumnType("int");

                    b.Property<int?>("TagId")
                        .HasColumnType("int");

                    b.HasKey("BourbonTagId");

                    b.HasIndex("BourbonId");

                    b.HasIndex("TagId");

                    b.ToTable("BourbonTag");
                });

            modelBuilder.Entity("ConnorBourbon.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DistilleryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("BrandId");

                    b.HasIndex("DistilleryId");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("ConnorBourbon.Models.Distillery", b =>
                {
                    b.Property<int>("DistilleryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("DistilleryId");

                    b.ToTable("Distilleries");
                });

            modelBuilder.Entity("ConnorBourbon.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("TagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("ConnorBourbon.Models.Bourbon", b =>
                {
                    b.HasOne("ConnorBourbon.Models.Brand", "Brand")
                        .WithMany("Bourbons")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("ConnorBourbon.Models.BourbonTag", b =>
                {
                    b.HasOne("ConnorBourbon.Models.Bourbon", "Bourbon")
                        .WithMany("JoinEntities")
                        .HasForeignKey("BourbonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConnorBourbon.Models.Tag", "Tag")
                        .WithMany("JoinEntities")
                        .HasForeignKey("TagId");

                    b.Navigation("Bourbon");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("ConnorBourbon.Models.Brand", b =>
                {
                    b.HasOne("ConnorBourbon.Models.Distillery", "Distillery")
                        .WithMany("Brands")
                        .HasForeignKey("DistilleryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distillery");
                });

            modelBuilder.Entity("ConnorBourbon.Models.Bourbon", b =>
                {
                    b.Navigation("JoinEntities");
                });

            modelBuilder.Entity("ConnorBourbon.Models.Brand", b =>
                {
                    b.Navigation("Bourbons");
                });

            modelBuilder.Entity("ConnorBourbon.Models.Distillery", b =>
                {
                    b.Navigation("Brands");
                });

            modelBuilder.Entity("ConnorBourbon.Models.Tag", b =>
                {
                    b.Navigation("JoinEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
